### ISSUE TITLE
Bug #2 - Export as CSV doesn't work for separate links

### ISSUE THREAD

**Issue by ghost** [near-linkdrop/ui.near-linkdrop#22]
Не працює експорт в CSV окремо виділених лінків. Створюється пустий CSV-файл з полями public key та link
![image](https://user-images.githubusercontent.com/89875524/137103693-a06cb9d9-0527-4d6a-9820-49e35d5346a1.png)

**Comment by eclipseeer** [comment]
Not relevant as far as we don't have checkboxes anymore
